### PR TITLE
refactors and fixing JSONtoXD when pipes are involved

### LINKED ISSUE #20: add tests for parsing pipes, look into why pipes aren't persisting once saved in the xword input

### PR DESCRIPTION
**Pull request by cod1r**
refactored replaceWordWithSymbol to have a
slightly more straight-forward control flow

refactored parseSplitsFromAnswer to be a little bit more clear in the documentation/comments and accounted for unicode characters taking up more than one utf-16 code-unit

fixed JSONtoXD when pipes are involved to go from xd -> json -> xd properly by doing replaceWordWithSymbol then adding back in the splits then replaceSymbolWithWord to get the final converted string which is correct

closes #20

### CODE REVIEW

**Comment by brookehus** [comment]
does it make sense to just merge it and see if it works (instead of testing it)?

File: lib/JSONtoXD.ts [hunk 1]
```diff
@@ -47,8 +56,12 @@ export const JSONToXD = (json: CrosswordJSON): string => {
   const getCluesXD = (clues: Clue[], direction: "A" | "D") => {
     return clues
       .map((clue) => {
-        const answer = addSplits(clue.answer, splitChar, clue.splits)
-        let line = `${direction}${clue.number}. ${clue.body} ~ ${answer}`
+        // not totally sure if meta having a "rebus" key 100% means that there are rebuses in the crossword
```
Comment (samanpwbb) [inline lib/JSONtoXD.ts:59]: looks like this is true - puzzles with no rebus will not have a rebus property

File: lib/xdparser2.ts [hunk 2]
```diff
@@ -387,33 +387,34 @@ export function xdParser(xd: string, strict = false, editorInfo = false): Crossw
...
 
-    if (tileIdx >= tiles.length) {
-      break
+    if (cur !== splitChar) {
+      tileIdx++
+    }
+
+    if (rebusAndNotSplitChar) {
+      // adding in the number of split characters to `i` as well because those dont count as tile characters
+      // and tile.word.length is a length not including splitChars
```
Comment (samanpwbb) [inline lib/xdparser2.ts:413]: makes sense!

File: lib/xdparser2.ts [hunk 3]
```diff
@@ -387,33 +387,34 @@ export function xdParser(xd: string, strict = false, editorInfo = false): Crossw
...
-  let offset = 0
-  for (let i = 0; i < word.length; i++) {
-    const cur = word[i + offset]
-
-    // don't increment tileIdx when adding splits
-    if (cur === splitChar) {
-      newWord += cur
-      continue
-    }
+  for (let i = 0; i < word.length && tileIdx < tiles.length;) {
```
Comment (samanpwbb) [inline lib/xdparser2.ts:394]: I don't know if I've ever seen a for loop written like this. A while loop might read a little clearer - not a blocker.

File: lib/xdparser2.ts [hunk 4]
```diff
@@ -642,23 +643,26 @@ function parseStyleCSSLike(str: string, xd: string, errorReporter: (msg: string,
...
  */
 function parseSplitsFromAnswer(answerWithSplits: string, splitCharacter?: string): number[] | undefined {
   if (!splitCharacter) return undefined
   const splits = []
-  let answer = ""
-  for (var i = 0; i < answerWithSplits.length; i++) {
-    if (answerWithSplits.charAt(i) === splitCharacter) {
-      splits.push(i - 1 - splits.length)
-      continue
+  const characters = [...answerWithSplits] // account for unicode characters like emojis that could take up more than one utf-16 unit
```
Comment (samanpwbb) [inline lib/xdparser2.ts:661]: Note that this will not cover all emojis – especially modern ones that have race, and gender, etc. You have to do something more complicated to really get an accurate count if there are emojis in the string (see https://github.com/orling/grapheme-splitter or https://github.com/mathiasbynens/emoji-regex for more robust options).

Since this is an improvement over what we had before, it is ok to merge, but we should at least file an issue about this because it will come up again.

File: tests/xdToJSON.test.ts [hunk 5]
```diff
@@ -456,3 +456,31 @@ O..O.#O.O##O..O
...
+
+it("can handle going back to an xd file WITH pipes in the original xd file", () => {
+  const xd = readFileSync(`./tests/puz/twitch-tv-with-pipes.xd`)
+  const json = xdToJSON(xd.toString())
+  const newXD = JSONToXD(json)
+  expect(newXD).toMatchInlineSnapshot(`
+"## Metadata
+
+title: Rebus split test
+author: Penelope Rudow
```
Comment (samanpwbb) [inline tests/xdToJSON.test.ts:468]: this is my cat's name, glad it lives on in test fixtures.

**Review by samanpwbb — APPROVED** [review]
